name: 'random-quote'
description: 'Puts a random quote on your README!'
author: 'Defective Detective'

inputs:
  GITHUB_TOKEN:
    description: 'Da GitHoob tokin'
    required: true

runs:
  using: 'node14'
  # I wanna use node14, any problem?
  main: './Source/Index.js'