name: random-quote
on:
  schedule:
    - cron: '*/10 * * * *'
    # Runs every 10 minutes since commit (or so is expected)
  workflow_dispatch:

jobs:
  putRandomQuote:
    runs-on: ubuntu-latest
    name: Time to mess up, by my goofiness. Credit goes to Random Quote

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: SpiderMath/Random-Quote-Workflow@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: git config --global user.name "Quote Bot"
      - run: git add README.md
      - run: git commit -m "Updated the Repository with a new quote :grin:"
      - run: git push
