name: Latest youtube videos
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/60 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-stack-overflow:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          commit_message: "Updated readme with the latest YouTube data"
          feed_list: "https://www.youtube.com/channel/UCuQvyfLaZOG4bPwEvqSYCLg"
